exclude = [
    "**/__pycache__",
    "**/.mypy_cache",
    "**/.pytest_cache",
    "**/.ruff_cache",
    "**/.venv",
    "prototype",
    "tests",
]
source_roots = ["."]
root_module = "ignore"

[external]
exclude = ["uvicorn"]

[rules]
unused_external_dependencies = "error"
